### ISSUE TITLE
วันที่ 19 ก.พ. มีเรียนไหมครับ

### ISSUE THREAD

**Issue by zartre** [up1/course_microservice_kmitl_2019#3]
วันที่ 19 กุมภาพันธ์นี้ ตรงกับวันมาฆบูชา ซึ่งเป็นวันที่พระภิกษุ 1,250 รูป ได้มาประชุมพร้อมกันยังวัดเวฬุวันโดยมิได้นัดหมาย

จึงอยากทราบว่ามีเรียนไหมครับ

**Comment by saiexx** [comment]
ห้องงานบริการแจ้งมาว่าเป็นวันหยุดราชการครับ หยุดเรียนทั้งม.
พรุ่งนี้จะมีเรียนไหมครับ?

**Comment by zartre** [comment]
ขอบคุณมากครับ

**Comment by up1** [comment]
ถ้าเจ้าหน้าที่หยุด ก็ต้องหยุดแล้วครับผม
